# Generated by Django 3.0.5 on 2021-01-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileedit',
            name='login_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
